---
title: "Homework 6"
author: Tu  Nguyen
output: github_document
---

This is my solution to HW6.

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2

Load and clean birth weight dataset
```{r}
birthweight_df = 
  read.csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace)
  )
```

From my knowledge, the mother's age and pre-pregnancy BMI can be the determinants of the baby's birth weight. 
I am interested in investigating the relationship between the mother's physique at delivery + the baby's gender and baby's birth weight. 


```{r}
proposed_model = lm(bwt ~ babysex + momage + ppbmi, data = birthweight_df)

```


